version: "1"
rules:                      # Array of rules
  - base: main            # Required. Target branch
    upstream: Araken-Sdn-Bhd:main    # Required. Must be in the same fork network.
    mergeMethod: merge  # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
label: ":arrow_heading_down: pull"  # Optional
conflictLabel: "merge-conflict" 
